// Clear form
export const CLEAR_FORM_ERROR = 'CLEAR_FORM_ERROR';

// Edit Profile
export const EDIT_PROFILE_LOADING = 'EDIT_PROFILE_LOADING';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

// Log out user
export const LOGOUT_USER = 'LOGOUT_USER';

// Request Password Reset
export const REQUEST_RESET_LOADING = 'REQUEST_RESET_LOADING';
export const REQUEST_RESET_SUCCESS = 'REQUEST_RESET_SUCCESS';
export const REQUEST_RESET_FAILURE = 'REQUEST_RESET_FAILURE';
export const CLEAR_REQUEST_RESET_MESSAGE = 'CLEAR_REQUEST_RESET_MESSAGE';

// Reset Password
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

// Signin User
export const SIGNIN_LOADING = 'SIGNIN_LOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

// Signup User
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Verify User Authentication
export const VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';
export const VERIFY_AUTH_FAILURE = 'VERIFY_AUTH_FAILURE';
export const VERIFY_AUTH_LOADING = 'VERIFY_AUTH_LOADING';

// Create Group
export const CREATE_GROUP_LOADING = 'CREATE_GROUP_LOADING';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';
export const RESET_CREATE_GROUP_STATUS = 'RESET_CREATE_GROUP_STATUS';

// Delete Group
export const DELETE_GROUP_LOADING = 'DELETE_GROUP_LOADING';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';

// Edit Group Info
export const EDIT_GROUP_INFO_LOADING = 'EDIT_GROUP_INFO_LOADING';
export const EDIT_GROUP_INFO_SUCCESS = 'EDIT_GROUP_INFO_SUCCESS';
export const EDIT_GROUP_INFO_FAILURE = 'EDIT_GROUP_INFO_FAILURE';

// Groups List
export const GROUPS_LIST_LOADING = 'GROUPS_LIST_LOADING';
export const GROUPS_LIST_SUCCESS = 'GROUPS_LIST_SUCCESS';
export const GROUPS_LIST_FAILURE = 'GROUPS_LIST_FAILURE';

// Get Group Users
export const GET_GROUP_USERS_LOADING = 'GET_GROUP_USERS_LOADING';
export const GET_GROUP_USERS_SUCCESS = 'GET_GROUP_USERS_SUCCESS';
export const GET_GROUP_USERS_FAILURE = 'GET_GROUP_USERS_FAILURE';

// In Group Page
export const IN_GROUP_TRUE = 'IN_GROUP_TRUE';
export const IN_GROUP_FALSE = 'IN_GROUP_FALSE';

// Leave Group
export const LEAVE_GROUP_LOADING = 'LEAVE_GROUP_LOADING';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAILURE = 'LEAVE_GROUP_FAILURE';

// Search Users
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';
export const SEARCH_USERS_LOADING = 'SEARCH_USERS_LOADING';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';

// Add User to Group
export const ADD_USER_LOADING = 'ADD_USER_LOADING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

// Remove User from Group
export const REMOVE_USER_LOADING = 'REMOVE_USER_LOADING';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';

// GEt Group Messages
export const GET_GROUP_MESSAGES_LOADING = 'GET_GROUP_MESSAGES_LOADING';
export const GET_GROUP_MESSAGES_SUCCESS = 'GET_GROUP_MESSAGES_SUCCESS';
export const GET_GROUP_MESSAGES_FAILURE = 'GET_GROUP_MESSAGES_FAILURE';

// Mark Messages as Read
export const MARK_READ_FAILURE = 'MARK_READ_FAILURE';

// Send Message
export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
